-- Tabelle für Admin
CREATE TABLE IF NOT EXISTS admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    benutzername VARCHAR(50) UNIQUE NOT NULL,
    passwort_hash VARCHAR(255) NOT NULL
);

-- Tabelle für Moderatoren
CREATE TABLE IF NOT EXISTS moderatoren (
    id INT AUTO_INCREMENT PRIMARY KEY,
    benutzername VARCHAR(50) UNIQUE NOT NULL,
    passwort_hash VARCHAR(255) NOT NULL,
    status ENUM('aktiv', 'inaktiv') NOT NULL DEFAULT 'aktiv'
);

-- Tabelle für Spenden
CREATE TABLE IF NOT EXISTS spenden (
    id INT AUTO_INCREMENT PRIMARY KEY,
    benutzername VARCHAR(255) NOT NULL,
    betrag DECIMAL(10,2) NOT NULL,
    ziel VARCHAR(100) NOT NULL,
    datum DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabelle für Spendenziele
CREATE TABLE IF NOT EXISTS ziele (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ziel VARCHAR(100) NOT NULL,
    gesamtbetrag DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    mindestbetrag DECIMAL(10,2) DEFAULT NULL,
    abgeschlossen TINYINT(1) NOT NULL DEFAULT 0,
    sichtbar TINYINT(1) NOT NULL DEFAULT 0
);

-- Tabelle für Einstellungen
CREATE TABLE IF NOT EXISTS einstellungen (
    schluessel VARCHAR(255) PRIMARY KEY,
    wert TEXT NOT NULL
);

-- Tabelle für Zeitzonen
CREATE TABLE IF NOT EXISTS zeitzonen (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Tabelle für den Spendenzeitraum
CREATE TABLE IF NOT EXISTS zeitraum (
    id INT AUTO_INCREMENT PRIMARY KEY,
    start DATETIME NOT NULL,
    ende DATETIME NOT NULL
);

-- Strukturanpassungen für bestehende Tabellen
DROP PROCEDURE IF EXISTS modify_columns_if_exist;
CREATE PROCEDURE modify_columns_if_exist()
BEGIN
    -- Admin Tabelle
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'admin' AND COLUMN_NAME = 'benutzername' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE admin MODIFY benutzername VARCHAR(50) UNIQUE NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'admin' AND COLUMN_NAME = 'passwort_hash' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE admin MODIFY passwort_hash VARCHAR(255) NOT NULL;
    END IF;

    -- Moderatoren Tabelle
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'moderatoren' AND COLUMN_NAME = 'benutzername' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE moderatoren MODIFY benutzername VARCHAR(50) UNIQUE NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'moderatoren' AND COLUMN_NAME = 'passwort_hash' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE moderatoren MODIFY passwort_hash VARCHAR(255) NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'moderatoren' AND COLUMN_NAME = 'status' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE moderatoren MODIFY status ENUM('aktiv', 'inaktiv') NOT NULL DEFAULT 'aktiv';
    END IF;

    -- Spenden Tabelle
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'spenden' AND COLUMN_NAME = 'benutzername' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE spenden MODIFY benutzername VARCHAR(255) NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'spenden' AND COLUMN_NAME = 'betrag' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE spenden MODIFY betrag DECIMAL(10,2) NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'spenden' AND COLUMN_NAME = 'ziel' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE spenden MODIFY ziel VARCHAR(100) NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'spenden' AND COLUMN_NAME = 'datum' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE spenden MODIFY datum DATETIME DEFAULT CURRENT_TIMESTAMP;
    END IF;

    -- Ziele Tabelle
    SET @renameColumn = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_NAME = 'ziele' 
        AND COLUMN_NAME = 'name' 
        AND TABLE_SCHEMA = DATABASE());
    SET @alterStmt = IF(@renameColumn > 0,
        'ALTER TABLE `ziele` CHANGE `name` `ziel` VARCHAR(100) NOT NULL',
        'SELECT "Spalte name existiert nicht"');
    PREPARE stmt FROM @alterStmt;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;

    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ziele' AND COLUMN_NAME = 'ziel' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE ziele MODIFY ziel VARCHAR(100) NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ziele' AND COLUMN_NAME = 'gesamtbetrag' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE ziele MODIFY gesamtbetrag DECIMAL(10,2) NOT NULL DEFAULT 0.00;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ziele' AND COLUMN_NAME = 'mindestbetrag' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE ziele MODIFY mindestbetrag DECIMAL(10,2) DEFAULT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ziele' AND COLUMN_NAME = 'abgeschlossen' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE ziele MODIFY abgeschlossen TINYINT(1) NOT NULL DEFAULT 0;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ziele' AND COLUMN_NAME = 'sichtbar' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE ziele MODIFY sichtbar TINYINT(1) NOT NULL DEFAULT 0;
    END IF;

    -- Einstellungen Tabelle
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'einstellungen' AND COLUMN_NAME = 'schluessel' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE einstellungen MODIFY schluessel VARCHAR(255) NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'einstellungen' AND COLUMN_NAME = 'wert' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE einstellungen MODIFY wert TEXT NOT NULL;
    END IF;

    -- Zeitzonen Tabelle
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'zeitzonen' AND COLUMN_NAME = 'name' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE zeitzonen MODIFY name VARCHAR(255) NOT NULL UNIQUE;
    END IF;

    -- Zeitraum Tabelle
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'zeitraum' AND COLUMN_NAME = 'start' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE zeitraum MODIFY start DATETIME NOT NULL;
    END IF;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'zeitraum' AND COLUMN_NAME = 'ende' AND TABLE_SCHEMA = DATABASE()) THEN
        ALTER TABLE zeitraum MODIFY ende DATETIME NOT NULL;
    END IF;
END;

CALL modify_columns_if_exist();
DROP PROCEDURE IF EXISTS modify_columns_if_exist; 